apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  # namespace: cpu-example
spec:
  containers:
    - name: cpu-demo-ctr
      image: busybox
      resources:
        limits:
          cpu: "0.25"
          memory: "128M"
        requests:
          cpu: "0.25"
          memory: "128M"
