apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeName: worker-02
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
